# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish on NPM

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Init checks
        run: |
            pkgname=ngx-tour-wizard
            pkgversion=$(node -p -e "require('./projects/$pkgname/package.json').version")
            echo detected project v $pkgversion
            latestpkgversion=$(npm view ${pkgname} version)
            echo detected latest v $latestpkgversion
            if [ pkgversion == latestpkgversion ]; then
                echo "Version already published!"
                exit 1;
            else
              echo "Version mismatch, we can proceed"
            fi
      - name: Install dependencies
        run: npm ci --ignore-optional --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Save build output
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          registry-url: https://registry.npmjs.org/
      - name: Download a single artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: dist-artifact
          path: dist
      - run: |
          ls -l
          echo $(ls -l)
          DIR=dist
          if [ -d "$DIR" ]; then
              echo "$DIR directory exists."
          else
            echo "$DIR directory does not exist."
            exit 1;
          fi
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
